# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pls4W8wgm-JUNjAAb6CVl-FDmooxx54j
"""

scores = input().split()  # 以空格分開每個成績
count = 0  # 計數用，紀錄不及格的人數

for s in scores:
    if int(s) < 60:      # 轉成整數後判斷是否不及格
        count += 1
avg = 0

for s in scores:
  avg += int(s)

ans = avg / len(scores)
print(count)
print(ans)